AWSTemplateFormatVersion: 2010-09-09
Description: Despliegue de Roles para API EKS  
Metadata:
  Authors:
    Description: Yoshieki Tanamachi yoshieki1992@gmail.com
  License: gg

Mappings:
  ServicePrincipals:
    aws-cn:
      ec2: ec2.amazonaws.com.cn
    aws:
      ec2: ec2.amazonaws.com

Resources:

  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy


  WorkersEKSAPIRol:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !FindInMap [ServicePrincipals, !Ref "AWS::Partition", ec2]
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Path: /


Outputs:
  RoleArn:
    Description: Rol utilizado por EKS 
    Value: !GetAtt eksClusterRole.Arn
    Export:
      Name: EKSAPIRoleArn
  
  RolWorkersEKS:
    Description: Rol de NodosWorkersEKS
    Value: !GetAtt WorkersEKSAPIRol.Arn
    Export:
      Name: WorkersEKSAPIRolArn

